spring:
  application:
    name: studentsapi

  r2dbc:
    url: r2dbc:h2:mem:///studentsdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    
logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function: INFO
        r2dbc: DEBUG
    reactor:
      netty:
        http:
          server: INFO

# Server configuration
server:
  port: 8080
  netty:
    connection-timeout: 20s
    idle-timeout: 60s
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain