-- Create students table
CREATE TABLE IF NOT EXISTS STUDENTS (
    ID BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    STATUS VARCHAR(10) NOT NULL CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    AGE SMALLINT NOT NULL
);
